# Generated by Django 6.0.5 on 2026-05-08 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Jedzenie'), ('chem', 'Chemia'), ('meds', 'Leki')], max_length=20, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='szt', max_length=20, verbose_name='Jednostka'),
        ),
    ]
